# Generated by Django 4.1 on 2024-02-28 06:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ParentApp', '0001_initial'),
        ('AdminApp', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_progress',
            fields=[
                ('progressid', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=250)),
                ('grade', models.CharField(max_length=10)),
                ('pro_date', models.DateField(auto_now_add=True, null=True)),
                ('applicationid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ParentApp.tbl_application')),
                ('daycareid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AdminApp.tbl_daycare')),
                ('subcategoryid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AdminApp.tbl_subcategory')),
            ],
        ),
        migrations.CreateModel(
            name='tbl_payment',
            fields=[
                ('paymentid', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=10)),
                ('pdate', models.DateField(auto_now_add=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ParentApp.tbl_application')),
                ('daycare', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AdminApp.tbl_daycare')),
            ],
        ),
    ]
