# Generated by Django 4.1 on 2024-02-28 06:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('AdminApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='login',
            fields=[
                ('LoginId', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('role', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='tbl_parent',
            fields=[
                ('parentid', models.AutoField(primary_key=True, serialize=False)),
                ('parentname', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=100)),
                ('phno', models.BigIntegerField()),
                ('address', models.CharField(max_length=100, null=True)),
                ('locationid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AdminApp.tbl_location')),
                ('loginid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GuestApp.login')),
            ],
        ),
    ]
