# Generated by Django 4.1 on 2024-02-28 06:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('GuestApp', '0001_initial'),
        ('AdminApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_daycare',
            name='login_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GuestApp.login'),
        ),
    ]
